export const DRIVERS = [
    { id: '1', name: "Max Verstappen", team: "Red Bull Racing", drivernumber: 3, image: require('../assets/images/drivers/verstappen.png')   },
    { id: '2', name: "Isaac Hadjar", team: "Red Bull Racing", drivernumber: 6, image: require('../assets/images/drivers/hadjar.png') },
    { id: '3', name: "Charles Leclerc", team: "Ferrari" , drivernumber: 16, image: require('../assets/images/drivers/leclerc.png')},
    { id: '4', name: "Lewis Hamilton", team: "Ferrari", drivernumber: 44, image: require('../assets/images/drivers/hamilton.png') },
    { id: '5', name: "George Russell", team: "Mercedes", drivernumber: 63, image: require('../assets/images/drivers/russell.png') },
    { id: '6', name: "Kimi Antonelli", team: "Mercedes", drivernumber: 12, image: require('../assets/images/drivers/antonelli.png') },
    { id: '7', name: "Lando Norris", team: "McLaren", drivernumber: 1, image: require('../assets/images/drivers/norris.png') },
    { id: '8', name: "Oscar Piastri", team: "McLaren", drivernumber: 81, image: require('../assets/images/drivers/piastri.png') },
    { id: '9', name: "Fernando Alonso", team: "Aston Martin", drivernumber: 14, image: require('../assets/images/drivers/alonso.png') },
    { id: '10', name: "Lance Stroll", team: "Aston Martin", drivernumber: 18, image: require('../assets/images/drivers/stroll.png') },
    { id: '11', name: "Franco Colapinto", team: "Alpine", drivernumber: 43, image: require('../assets/images/drivers/colapinto.png') },
    { id: '12', name: "Pierre Gasly", team: "Alpine", drivernumber: 10, image: require('../assets/images/drivers/gasly.png') },
    { id: '13', name: "Valtteri Bottas", team: "Cadillac", drivernumber: 77, image: require('../assets/images/drivers/bottas.png') },
    { id: '14', name: "Sergio Perez", team: "Cadillac", drivernumber: 11, image: require('../assets/images/drivers/perez.png') },
    { id: '15', name: "Liam Lawson", team: "Racing Bulls", drivernumber: 30, image: require('../assets/images/drivers/lawson.png') },
    { id: '16', name: "Arvid Lindblad", team:"Racing Bulls" , drivernumber :41, image :require("../assets/images/drivers/lindblad.png")},
    { id: '17', name: "Esteban Ocon", team: "Haas", drivernumber: 31, image: require('../assets/images/drivers/ocon.png') },
    { id: '18', name: "Oliver Bearman", team: "Haas", drivernumber: 87, image: require('../assets/images/drivers/bearman.png') },
    { id: '19', name: "Carlos Sainz", team: "Williams", drivernumber: 55, image: require('../assets/images/drivers/sainz.png') },
    { id: '20', name: "Alex Albon", team: "Williams", drivernumber: 23, image: require('../assets/images/drivers/albon.png') },
    { id: '21', name: "Nico Hulkemberg", team: "Audi", drivernumber: 27, image: require('../assets/images/drivers/hulkemberg.png') },
    { id: '22', name: "Gabriel Bortoleto", team: "Audi", drivernumber: 5, image: require('../assets/images/drivers/bortoleto.png') },
];