export const FLAGS_INFO = [
  { name: 'Australia', image: require('../assets/images/flags/australia.png') },
    { name: 'Belgium', image: require('../assets/images/flags/belgium.png') },
    { name: 'Bahrain', image: require('../assets/images/flags/bahrain.png') },
    { name: 'Saudi Arabia', image: require('../assets/images/flags/saudi_arabia.png') },
    { name: 'China', image: require('../assets/images/flags/china.png') },
    { name: 'Japan', image: require('../assets/images/flags/japan.png') },
    { name: 'Italy', image: require('../assets/images/flags/italy.png') },
    { name: 'Monaco', image: require('../assets/images/flags/monaco.png') },
    { name: 'Canada', image: require('../assets/images/flags/canada.png') },
    { name: 'Barcelona', image: require('../assets/images/flags/spain.png') },
    { name: 'Austria', image: require('../assets/images/flags/austria.png') },
    { name: 'Hungary', image: require('../assets/images/flags/hungary.png') },
    { name: 'Netherlands', image: require('../assets/images/flags/netherlands.png') },
    { name: 'Mexico', image: require('../assets/images/flags/mexico.png') },
    { name: 'Brazil', image: require('../assets/images/flags/brazil.png') },
    { name: 'Texas', image: require('../assets/images/flags/usa.png') },
    { name: 'Singapore', image: require('../assets/images/flags/singapore.png') },
    { name: 'Qatar', image: require('../assets/images/flags/qatar.png') },
    { name: 'Abu Dhabi', image: require('../assets/images/flags/abu_dhabi.png') },
    { name: 'Miami', image: require('../assets/images/flags/usa.png') },
    { name: 'Great Britain', image: require('../assets/images/flags/great_britain.png') },
    { name: 'Azerbaijan', image: require('../assets/images/flags/azerbaijan.png') },
    { name: 'Las Vegas', image: require('../assets/images/flags/usa.png') },
    { name: 'Madrid', image: require('../assets/images/flags/spain.png') },
];