export const TRACKSINFO = [
    { id: '1',name: 'Australia', image: require('../assets/images/tracks_info/australia.png') },
    { id: '2',name: 'China', image: require('../assets/images/tracks_info/china.png') },
    { id: '3',name: 'Japan', image: require('../assets/images/tracks_info/japan.png') },
    { id: '4',name: 'Bahrain', image: require('../assets/images/tracks_info/bahrain.png') },
    { id: '5',name: 'Saudi Arabia', image: require('../assets/images/tracks_info/saudi_arabia.png') },
    { id: '6',name: 'Miami', image: require('../assets/images/tracks_info/miami.png') },
    { id: '7',name: 'Canada', image: require('../assets/images/tracks_info/canada.png') },
    { id: '8',name: 'Monaco', image: require('../assets/images/tracks_info/monaco.png') },
    { id: '9',name: 'Barcelona', image: require('../assets/images/tracks_info/barcelona.png') },
    { id: '10',name: 'Austria', image: require('../assets/images/tracks_info/austria.png') },
    { id: '11',name: 'Great Britain', image: require('../assets/images/tracks_info/great_britain.png') },
    { id: '12',name: 'Belgium', image: require('../assets/images/tracks_info/belgium.png') },
    { id: '13',name: 'Hungary', image: require('../assets/images/tracks_info/hungary.png') },
    { id: '14',name: 'Netherlands', image: require('../assets/images/tracks_info/netherlands.png') },
    { id: '15',name: 'Italy', image: require('../assets/images/tracks_info/italy.png') },
    { id: '16',name: 'Madrid', image: require('../assets/images/tracks_info/madrid.png') },
    { id: '17',name: 'Azerbaijan', image: require('../assets/images/tracks_info/azerbaijan.png') },
    { id: '18',name: 'Singapore', image: require('../assets/images/tracks_info/singapore.png') },
    { id: '19',name: 'Texas', image: require('../assets/images/tracks_info/texas.png') },
    { id: '20',name: 'Mexico', image: require('../assets/images/tracks_info/mexico.png') },
    { id: '21',name: 'Brazil', image: require('../assets/images/tracks_info/brazil.png') },
    { id: '22',name: 'Las Vegas', image: require('../assets/images/tracks_info/las_vegas.png') },
    { id: '23',name: 'Qatar', image: require('../assets/images/tracks_info/qatar.png') },
    { id: '24',name: 'Abu Dhabi', image: require('../assets/images/tracks_info/abu_dhabi.png') },
]